"""Adding public_id to post

Revision ID: 33942a318546
Revises: b3b3e7594e5b
Create Date: 2020-10-02 18:56:54.811280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33942a318546'
down_revision = 'b3b3e7594e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'post', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'public_id')
    # ### end Alembic commands ###
