"""empty message

Revision ID: 7b959a514fe1
Revises: abecfe706c89
Create Date: 2020-10-08 16:51:03.515350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b959a514fe1'
down_revision = 'abecfe706c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_blacklist_tokens_token'), ['token'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_src', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_images_full_src'), ['full_src'])
        batch_op.create_unique_constraint(batch_op.f('uq_images_path'), ['path'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_posts_public_id'), ['public_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_public_id'), ['public_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_public_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_public_id'), type_='unique')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_images_path'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_images_full_src'), type_='unique')
        batch_op.drop_column('full_src')

    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_blacklist_tokens_token'), type_='unique')

    # ### end Alembic commands ###
