"""Adding created_on

Revision ID: b3b3e7594e5b
Revises: 941d59aaf86e
Create Date: 2020-10-02 16:36:33.355963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b3e7594e5b'
down_revision = '941d59aaf86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('created_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_on')
    op.drop_column('image', 'created_on')
    # ### end Alembic commands ###
